@OrderApi_HostAddress = http://localhost:5198
@Bearer_Token = BURAYA_ACCESS_TOKEN_YAPIŞTIRIN

### Herkese açık
GET {{OrderApi_HostAddress}}/orders/public
Accept: application/json

###
### Tüm siparişler (Admin)
GET {{OrderApi_HostAddress}}/orders
Authorization: Bearer {{Bearer_Token}}
Accept: application/json

###
### Benim siparişlerim (Admin veya User)
GET {{OrderApi_HostAddress}}/orders/my
Authorization: Bearer {{Bearer_Token}}
Accept: application/json

###
### Sipariş oluştur (Admin veya User)
POST {{OrderApi_HostAddress}}/orders
Authorization: Bearer {{Bearer_Token}}
Content-Type: application/json
Accept: application/json

{
  "productName": "Örnek Ürün",
  "quantity": 2,
  "customerName": "Müşteri Adı"
}

###
